### ISSUE TITLE
System.Web.Caching.Cache implementation of ICacheClient

### ISSUE THREAD

**Issue by cpalm** [exceptionless/Foundatio#2]
Love the building blocks!

It is not a bug, it is a feature request

It would be really cool, if there could be an implementation of ICacheClient via System.Web.Caching.Cache

**Comment by niemyjski** [comment]
Please correct me if I'm wrong but doesn't the [`System.Web.Caching.Cache`](https://msdn.microsoft.com/en-us/library/system.web.caching.cache%28v=vs.110%29.aspx) just cache per process? If this is the case it would be better to just use our `InMemoryCacheClient` client as it's doing the same thing without the overhead of `System.Web.Caching.Cache`.

**Comment by cpalm** [comment]
You are absolutely right. Thanks for the quick answer.

I was not using the InMemoryCacheClient as a singleton eg.
kernel.Bind<ICacheClient>().To<InMemoryCacheClient>().InSingletonScope();

**Comment by niemyjski** [comment]
No problem! Please let us know if you have any other questions!
