### ISSUE TITLE
Queue Management Improvements

### ISSUE THREAD

**Issue by jamie94bc** [exceptionless/Foundatio#25]
Our current implementation of `IQueue` has a [DeleteQueueAsync](https://github.com/exceptionless/Foundatio/blob/master/src/Azure/Queues/AzureServiceBusQueue.cs#L68) method which actually recreates the queue.

This clearly isn't expected behaviour (meaning we can't delete the queue easily in the test tear town) and in addition, we are also performing remote calls in the constructor of the queue which isn't ideal.

We could introduce an additional interface to manage the queues, although we'd have to specifically create every queue and inject it into the container - and the bootstrapper class therefore must ideally be async compatible.

```c#
public interface IQueueManager<TQueue> where TQueue : IQueue<T> {
    Task<TQueue> CreateQueueAsync(string queueName /* other params */);
    Task<bool> QueueExistsAsync(string queueName);
    Task DeleteQueueAsync(string queueName);
}
``` 

A big down side to this would be it would also make it more difficult to specify additional constructor params for the queue (as used in AzureStorageQueue to control poll interval).

**Comment by niemyjski** [comment]
Yeah, I think that queue creation should happen automatically by the queues upon first use. Delete definitely shouldn't recreate the queue but maybe set a flag saying it needs to be recreated. We could just set some internals to null on delete and every method has an Ensure() method to ensure it's recreated. Thoughts?

**Comment by ejsmith** [comment]
I actually had an interface together that was super similar to this before, but bailed out due to time constraints. I think I had just an object parameter for options on the CreateQueue method. That way you can pass any type of object in for configuration that the various implementations could cast and use how they wanted. I am going to try and dig that up and see if there were any good ideas.

**Comment by moswald** [comment]
While I'm getting my hands dirty with #36, I can take a look at having the delete be more permanent.

**Comment by niemyjski** [comment]
This has been fixed in master and will be released via nuget shortly
