### ISSUE TITLE
Create strong name nuget packages

### ISSUE THREAD

**Issue by ytkaczyk** [exceptionless/Foundatio#31]
Would it be possible to create strong name versions of the nuget packages? I am using Signal.Redis which has a dependency on StackExchange.Redis.StrongName while Foundation.Redis has a dependency on StackExchange.Redis. I can build the Foundation solution with the proper dependency but I would imagine I am not the only one having this issue and the community could benefit from such strong named nuget packages. Thank you.

**Comment by ejsmith** [comment]
Yeah, we will probably need to have signed packages. Think we are going to wait until we move to the new project.json format and see if it's easier to do at that point.

**Comment by ytkaczyk** [comment]
Thank you for your quick reply. This makes sense. I'll build the solution with signed dependencies in the mean time. 
Best regards.

**Comment by niemyjski** [comment]
@ytkaczyk we moved to the new project format. Is there any chance you could submit a pr for this?

**Comment by niemyjski** [comment]
@ytkaczyk we've officially have updated to the new cs proj format, would you be interested in adding a pr for this. I'm going to close this but feel free to reopen it with a pr or if additional people request it will change the priority.
