### ISSUE TITLE
Add Job backend implementation for Quartz, Hangfire, Azure, AWS

### ISSUE THREAD

**Issue by mobydi** [exceptionless/Foundatio#33]
You can provide the IJob interface and some different job implementations that derive from
1. Quartz
2. Hangfire
3. Azure/AWS
4. Memory

**Comment by niemyjski** [comment]
Are you looking for something specific? What we are do now is we create a console application and deploy that into our azure webjobs:

- https://github.com/exceptionless/Exceptionless/tree/master/Source/Jobs/EventPost
- https://github.com/exceptionless/Foundatio/tree/master/src/Test/SampleJob
- https://exceptionless.com/better-approach-running-azure-webjobs/

**Comment by niemyjski** [comment]
@mobydi does this work for you?

**Comment by niemyjski** [comment]
If you have any questions on the various implementations feel free to leave a message here or on our gitter channel: http://gitter.im/exceptionless/Discuss as we would be more than happy to help you!
