### ISSUE TITLE
Create async initialization method for AzureServiceBusQueue.

### ISSUE THREAD

**Issue by moswald** [exceptionless/Foundatio#36]
A lot of the `Microsoft.ServiceBus.NamespaceManager` methods called in the `AzureServiceBusQueue` constructor have `async` counterparts. Since constructors can't be `async`, I propose deprecating the current constructor (shakes fist at semver) and adding a new private one that does very little. Then introduce a new factory method: `static async Task<AzureServiceBusQueue>` factory method that does all the same work the current constructor does synchronously.

**Comment by ejsmith** [comment]
Yeah, probably bad to be doing a bunch of heavy calls in the constructor. I think a generalized lazy initialization pattern would be good.

Do you want to take a stab at this and create a pull request for it?

**Comment by moswald** [comment]
I was planning on starting it tomorrow when I got back to the office. :) I just wanted to get the conversation rolling before then.

**Comment by ejsmith** [comment]
Awesome! Thank you.

**Comment by jamie94bc** [comment]
This relates to #25

**Comment by moswald** [comment]
Regarding #25, I'll take a look at having an optional parameter that makes the queue lazy - it will create and connect only on the first enqueue/dequeue.

**Comment by niemyjski** [comment]
Awesome :) I wonder if we always need to setup the connections/subscriptions immediately. How would you know there is an item to dequeue in a distributed environment.

**Comment by jamie94bc** [comment]
@niemyjski I think that would be handled by the `StartWorking()` method? I assume @moswald is thinking about adding something like a `EnsureQueueAsync()` method that each public API calls first.

**Comment by moswald** [comment]
@niemyjski I would expect that if there's nothing to dequeue, it would just time out.

**Comment by niemyjski** [comment]
@moswald Yeah! Not sure what I was thinking before (long night of playing quantum break). I think having this would be great and it looks like it would be super simple to implement.

**Comment by niemyjski** [comment]
This has been fixed in master and will be released via nuget shortly
