### ISSUE TITLE
Add support for DefaultMessageTimeToLive and AutoDeleteOnIdle in AzureServiceBusQueue

### ISSUE THREAD

**Issue by trbenning** [exceptionless/Foundatio#39]
Obviously there are many more "Azure ServiceBus Queue" specific properties that are unsupported, but these 2 are the ones I need right now. Do you guys have a strategy for how you might support these types of properties moving forward?

I started to do a pull request to set the properties via the constructor, but bolting on properties piecemeal seems like an unsustainable strategy.

**Comment by jamie94bc** [comment]
Up until now we've tried to implement equal functionality on each implementation (eg. storage queue has it's own implementation of deadletter, service bus supports this "natively").

Personally i don't have an issue with having different constructor properties per implementation as long as the exposed implementation (`IQueue<T>`) works the same. If we were to implement this across the board, it would be an option in the constructor (either an additional argument or using a `Options` object if this gets too unwieldy).

**Comment by niemyjski** [comment]
Thanks for the pr!
