### ISSUE TITLE
Roadmap suggestion

### ISSUE THREAD

**Issue by tonymobster** [exceptionless/Foundatio#5]
For the roadmap you could mirror the [go-kit](https://github.com/go-kit/kit) roadmap.

**Comment by niemyjski** [comment]
@tonymobster where is their roadmap? I looked at the repo but I don't see it.

**Comment by tonymobster** [comment]
Yeah sorry, I was referring to the various [components] (https://github.com/go-kit/kit#component-status) of the toolkit, the applicable ones.

**Comment by niemyjski** [comment]
Thanks, it's similar to what we do but we could make ours better.

**Comment by tonymobster** [comment]
My sentiments exactly

**Comment by niemyjski** [comment]
I'm going to close this as we are going to try and start using milestones for all of our work.
