### ISSUE TITLE
Using Fondatio with .net 4.5.2

### ISSUE THREAD

**Issue by lynnroth** [exceptionless/Foundatio#65]
I'm looking to be able to use some of the great functionality that I just found in the Foundatio library.

However, we have an application that we currently support on .net 4.5.2.  It seems that a few months ago there was a change that Foundatio only supports 4.6 and later.  

Is my only choice to use v4.1?  Any plans to backport fixes to this branch for people who can't move ahead to 4.6 at this time?

Thanks.

**Comment by niemyjski** [comment]
At the time it was brought to our attention by @StephenCleary that it's best to be on .NET 4.6 due to some async / await issues (https://github.com/StephenCleary/AsyncEx/issues/48) that could arise. For that reason and the fact that we feel that any new project that would be starting out would be on 4.6 we changed it from 4.5.2 to 4.6.

Is there any reason you cannot move to 4.6?

**Comment by niemyjski** [comment]
cc @ejsmith

**Comment by lynnroth** [comment]
We share core code between our Windows application and our web applications.  So, in order to update, we have to get all the customer systems updated to 4.6 prior to the switchover. 

It's not that we can't move to 4.6, but we have to give our customers time to get it installed on all of their systems.  

This may be enough of a reason, but we are currently evaluating.  

I'm primarily looking at the RedisHybridCacheClient as this gives such nice functionality of keeping local caches in sync between multiple systems.

**Comment by ejsmith** [comment]
I am fine with us supporting 4.5 as a platform target. @lynnroth would you mind submitting a PR?

**Comment by lynnroth** [comment]
I'll discuss with the team on our timing of going to 4.6.  If it is soon, we can leverage the 4.1 version of Foundatio until we can get to 4.6.

**Comment by lynnroth** [comment]
So, I started looking at adding 452 support back in .  I believe that this commit (at least) took away an easy way of getting back to 4.5
https://github.com/exceptionless/Foundatio/commit/549a044e01dc3285aa27dca3fa95d83a6d635719

If that isn't the case, please let me know.

Given that, and that we should be able to move fairly quickly to 4.6, I believe we will use 4.1 until we can get the framework updated to 4.6.

Thanks for your help.

**Comment by niemyjski** [comment]
Yeah, that probably would be one of the only major things that would need to changed. I'm going to close this for now, unless you want to take a stab at a pr then please reference this issue. If there is anything we can help you with please let us know.

**Comment by niemyjski** [comment]
Also, please feel free to check out our slack channel: http://slack.exceptionless.com
