### ISSUE TITLE
will it support log4net?

### ISSUE THREAD

**Issue by capqueen** [exceptionless/Foundatio#67]
I use log4net in my project, so I wonder if Foundatio.Loggging will have a log4net appder?

**Comment by niemyjski** [comment]
Currently we only have one written for nlog (as that's what we use for our projects internally).  We'd be willing to accept a pull request for this.  I'm going to close this but we would be more than happy to accept a pr for this.

Here is a link to our nlog target: https://github.com/exceptionless/Foundatio/tree/master/src/Foundatio.Logging.NLog
