### ISSUE TITLE
Support for on premise WindowsServer Service Bus

### ISSUE THREAD

**Issue by dpvreony** [exceptionless/Foundatio#71]
Hi

We have a need to support https://www.nuget.org/packages/ServiceBus.v1_1/ I have done a fork (https://github.com/exceptionless/Foundatio/compare/master...dpvreony-forks:master), it's pretty much a carbon copy of the existing Azure project. I can raise a PR if you're happy.

Thanks

**Comment by ejsmith** [comment]
I think they are discontinuing this product, no?

**Comment by niemyjski** [comment]
As long as it's a supported product (looks like the last update was last year, wonder if there are updates in server 16) and there are tests for it and we can test it on appveyor I think we'd be more than happy to accept a pr for it.

**Comment by niemyjski** [comment]
It looks like it is dead but will live on as part of the on premise Azure Stack. I'd like to include support for this, but not sure how much sense it makes maintaining this when the project is officially dead as of next year. Do you have plans on moving to the azure stack? It would be great to have a basic service bus client that supports amqp :) or even a more targeted one towards the azure stack. Would you be interested in submitting a new pr for this? In the mean time I'm going to close this as the product is officially dead. Please feel free to join our slack :).

http://stackoverflow.com/questions/35401858/is-service-bus-for-windows-server-dead 

https://azure.microsoft.com/en-us/blog/collaboration-and-federation-azure-service-bus-messaging-on-premises-futures/


Edit: It is officially dead. Microsoft "will not provide an immediate successor for the standalone Service Bus for Windows Server 1.1 product" and it "and will go out of mainstream support on January 9, 2018".

Original answer (Aug 4 '16):

The short answer: Service Bus for Windows Server does have a future as part of Azure Stack but it is not going to be free and will not happen this year (2016).

Apparently the roadmap was announced on May 12 at Integrate 2016 during Clemens Vasters's Service Bus – Roadmap, What’s next? talk. You can listen to the announcements related to Service Bus at about 40:35.

**Comment by ejsmith** [comment]
The new client they are working on for .net core is an AMQP client. That is what we should work on.
