### ISSUE TITLE
How to declare rabbitmq hostname

### ISSUE THREAD

**Issue by cuibty** [exceptionless/Foundatio#73]

**Comment by niemyjski** [comment]
@barkhashah I don't see this as part of the sample so I'm assuming it's local host. Do we need to add a parameter for this??

**Comment by barkhashah** [comment]
Hey Blake
Sorry for the late reply. Thats a good point you brought up. I think this went unnoticed but currently library is assuming localhost as a place where the endpoint ( rabbitmq server ) is. We should have passed that as a parameter in the constructor and use it as an argument to Endpoint in the ConnectionFactory or use the uri.

**Comment by barkhashah** [comment]
Argument needs to be passed in this method:
        private IConnection CreateConnection() {
            IConnectionFactory factory = new ConnectionFactory();
            factory.UserName = _userName;
            factory.Password = _password;
            return factory.CreateConnection();
        }

factory.CreateConnection should take the array of endpoint

**Comment by niemyjski** [comment]
@cuibty / @barkhashah any chance we could get a pr for this :)?

**Comment by barkhashah** [comment]
:)... Its easy but I would have to ask my program manager if i can put some time on it . I started to work on this because we had a need for it and then just when i was done requirement changed and we are no longer working on any project that uses rabbitmq. Can @cuibty  spend some time? :)

**Comment by barkhashah** [comment]
@cuibty - Please let me know if you have any bandwidth else I can take this up during the weekend.

**Comment by niemyjski** [comment]
@cuibty @barkhashah Any updates on this? I can add it to my list but would like to involve the community as much as possible :)

**Comment by niemyjski** [comment]
Sorry for taking so long to add this functionality. I've just published a patch for this.
