### ISSUE TITLE
MessageBus Subscriptions

### ISSUE THREAD

**Issue by Romanx** [exceptionless/Foundatio#94]
Hey,

Great foundations here. I'd be tempted to use this for a project i'm working on (which currently just uses the standard ServiceBus nuget) however we're using the Topics and Subscription functionality. 

The `AzureServiceBusMessageBus` implementation uses the subscription to determine the channel to push to the multiple subscribers however there doesn't seem to be a way to listen to individual subscriptions being exposed. Would there be any interest in this functionality being added?

**Comment by niemyjski** [comment]
If I understand you correctly you can do this today (we'll at least in the cloud watch branch). So we provide a Topic name that you can set and when you call subscribe we'll only listen on that single subscription to that topic.  Out of the box, we'll create random subscription names to the same topic, but if you manually specify the topic name we should respect that. Is that what you are looking for?

**Comment by Romanx** [comment]
Hi @niemyjski that does seem exactly what i'm looking for. I hadn't looked anywhere but master. Feel free to close this and i'll have a play when it gets merged into master and feedback any problems I find

**Comment by niemyjski** [comment]
If you add our nightly feed (http://myget.org/gallery/exceptionless) you can get access to this code. If you set the `SubscriptionName` options setting then we'll only listen on that subscription name, otherwise we'll use a random subscription id and fanout :) If this doesn't help please let me know and we'll reopen this issue.
